services:
  mongo-tournament:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_tournament_data:/data/db

  mysql-player:
    image: mysql:latest
    ports:
      - 1111:3306
    volumes:
      - mysql_player_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  mysql-club:
    image: mysql:latest
    ports:
      - 2222:3306
    volumes:
      - mysql_club_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  tournament-service:
    depends_on:
      - mongo-tournament
    image: sebastianvg153/tournament-service
    ports:
      - 8080:8080
    links:
      - mongo-tournament
    environment:
      MONGODB_HOST: mongo-tournament
      MONGODB_PORT: 27017

  club-service:
    depends_on:
      - mysql-club
    image: sebastianvg153/club-service
    ports:
      - 8082:8082
    links:
      - mysql-club
    environment:
      MYSQL_DB_HOST: mysql-club
      MYSQL_DB_PORT: 2222
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: 12345

  player-service:
    depends_on:
      - mysql-player
    image: sebastianvg153/player-service
    ports:
      - 8081:8081
    links:
      - mysql-player
    environment:
      TOURNAMENT_SERVICE_BASEURL: tournament-service:8080
      CLUB_SERVICE_BASEURL: club-service:8082
      MYSQL_DB_HOST: mysql-player
      MYSQL_DB_PORT: 1111
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: 12345

  api-gateway:
    depends_on:
      - tournament-service
      - club-service
      - player-service
    image: sebastianvg153/api-gateway
    ports:
      - 8083:8083
    links:
      - tournament-service
      - club-service
      - player-service
    environment:
      TOURNAMENT_SERVICE_BASEURL: tournament-service:8080
      CLUB_SERVICE_BASEURL: club-service:8082
      PLAYER_SERVICE_BASEURL: player-service:8081

volumes:
  mongodb_tournament_data:
  mysql_player_data:
  mysql_club_data:
