server:
    port: 8083

logging:
    level:
        root: INFO
        org.springframework.cloud.gateway: TRACE
        org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
        reactor.netty: TRACE

spring:
    cloud:
        gateway:
            routes:
                - id: player-post
                  uri: http://${PLAYER_SERVICE_BASEURL:localhost:8081}
                  predicates:
                      - Path=/player/post
                      - Method=POST
                  filters:
                      - SetPath=/api/player/post
