server:
    port: 8083

logging:
    level:
        root: INFO
        org.springframework.cloud.gateway: TRACE
        org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
        reactor.netty: TRACE

spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENTID}
              client-secret: ${GOOGLE_CLIENTSECRET}
              scope: openid,profile,email
        resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
    cloud:
        gateway:
            routes:
                - id: player-get-all
                  uri: http://${PLAYER_SERVICE_BASEURL:localhost:8081}
                  predicates:
                      - Path=/player/get/all
                      - Method=GET
                  filters:
                      - SetPath=/api/player/get/all
                - id: player-post
                  uri: http://${PLAYER_SERVICE_BASEURL:localhost:8081}
                  predicates:
                      - Path=/player/post
                      - Method=POST
                  filters:
                      - SetPath=/api/player/post
                - id: player-get-id
                  uri: http://${PLAYER_SERVICE_BASEURL:localhost:8081}
                  predicates:
                      - Path=/player/get/{id}
                      - Method=GET
                  filters:
                      - SetPath=/api/player/get/{id}
                - id: player-put-id
                  uri: http://${PLAYER_SERVICE_BASEURL:localhost:8081}
                  predicates:
                        - Path=/player/put/{id}
                        - Method=GET,PUT,DELETE
                  filters:
                        - SetPath=/api/player/put/{id}
                - id: player-delete-id
                  uri: http://${PLAYER_SERVICE_BASEURL:localhost:8081}
                  predicates:
                        - Path=/player/delete/{id}
                        - Method=GET,DELETE
                  filters:
                        - SetPath=/api/player/delete/{id}
                - id: club-service
                  uri: http://${CLUB_SERVICE_BASEURL:localhost:8082}
                  predicates:
                        - Path=/club/get/all
                        - Method=GET
                  filters:
                        - SetPath=/api/club/get/all
                - id: club-service
                  uri: http://${CLUB_SERVICE_BASEURL:localhost:8082}
                  predicates:
                        - Path=/club/get/{id}
                        - Method=GET
                  filters:
                        - SetPath=/api/club/get/{id}
                - id: club-service
                  uri: http://${CLUB_SERVICE_BASEURL:localhost:8082}
                  predicates:
                        - Path=/club/post
                        - Method=POST
                  filters:
                        - SetPath=/api/club/post
                - id: club-service
                  uri: http://${CLUB_SERVICE_BASEURL:localhost:8082}
                  predicates:
                        - Path=/club/put/{id}
                        - Method=GET,PUT,DELETE
                  filters:
                        - SetPath=/api/club/put/{id}
                - id: club-service
                  uri: http://${CLUB_SERVICE_BASEURL:localhost:8082}
                  predicates:
                        - Path=/club/delete/{id}
                        - Method=GET,DELETE
                  filters:
                        - SetPath=/api/club/get/all

                - id: tournament-service
                  uri: http://${TOURNAMENT_SERVICE_BASEURL:localhost:8080}
                  predicates:
                        - Path=/tournament/get/all
                        - Method=GET
                  filters:
                        - SetPath=/api/tournament/get/all
                - id: tournament-service
                  uri: http://${TOURNAMENT_SERVICE_BASEURL:localhost:8080}
                  predicates:
                        - Path=/tournament/get/{id}
                        - Method=GET
                  filters:
                        - SetPath=/api/tournament/get/{id}
                - id: tournament-service
                  uri: http://${TOURNAMENT_SERVICE_BASEURL:localhost:8080}
                  predicates:
                        - Path=/tournament/post
                        - Method=POST
                  filters:
                        - SetPath=/api/tournament/post
                - id: tournament-service
                  uri: http://${TOURNAMENT_SERVICE_BASEURL:localhost:8080}
                  predicates:
                        - Path=/tournament/put/{id}
                        - Method=GET,PUT,DELETE
                  filters:
                        - SetPath=/api/tournament/put/{id}
                - id: tournament-service
                  uri: http://${TOURNAMENT_SERVICE_BASEURL:localhost:8080}
                  predicates:
                        - Path=/tournament/delete/{id}
                        - Method=GET,DELETE
                  filters:
                        - SetPath=/api/tournament/delete/{id}