name: Build and deliver containers

on: push

jobs:
  tournamentservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver tournament-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, test and package project
        working-directory: ./Tournament-service
        run: mvn package -DskipTests

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/tournament-service:latest ./Tournament-service

      - name: Upload container to Docker Hub with push
        run: docker push ${{ secrets.DOCKER_USER }}/tournament-service:latest
  
  clubservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver club-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, test and package project
        working-directory: ./Club-service
        run: mvn package -DskipTests
      
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/club-service:latest ./Club-service

      - name: Upload container to Docker Hub with push
        run: docker push ${{ secrets.DOCKER_USER }}/club-service:latest

  playerservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver player-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./Player-service
        run: mvn package -DskipTests

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/player-service:latest ./Player-service

      - name: Upload container to Docker Hub with push
        run: docker push ${{ secrets.DOCKER_USER }}/player-service:latest

  apigateway:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver api-gateway container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./api-gateway
        run: mvn package -DskipTests

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p {{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/api-gateway:latest ./api-gateway

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/api-gateway:latest